name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]   # релизы вида v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Генерим теги и метки
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: rasnaut/webcalculator-dbclient-python
        tags: |
          # релизный тег: v1.2.3 -> 1.2.3
          type=ref,event=tag,pattern=v{{version}}
          # для main: latest
          type=raw,value=latest,enable={{is_default_branch}}
          # всегда добавляем sha-<короткий>
          type=sha,format=short,prefix=sha-
        labels: |
          org.opencontainers.image.title=webcalculator-dbclient-python
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
